name: declops
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
    - autodocodec
    - autodocodec-yaml
    - envparse
    - optparse-applicative
    - path
    - path-io
    - text
    - validity
    - validity-path
    - yaml

executables:
  declops:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - declops

tests:
  declops-test:
    main: Spec.hs
    build-tools: sydtest-discover
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - declops
    - genvalidity-path
    - genvalidity-sydtest
    - path
    - path-io
    - sydtest
    - text
