name: declops
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  declops-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - declops

tests:
  declops-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - declops
