name: declops
version: 0.0.0.0

extra-source-files:
- test_resources/**/*

data-files:
- nix-bits/**/*.nix

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
    - aeson
    - aeson-pretty
    - autodocodec
    - autodocodec-yaml
    - bytestring
    - containers
    - declops-provider
    - declops-provider-local
    - declops-provider-virtualbox
    - envparse
    - monad-logger
    - mtl
    - optparse-applicative
    - path
    - path-io
    - persistent
    - persistent-sqlite
    - safe-coloured-text
    - safe-coloured-text-layout
    - safe-coloured-text-terminfo
    - text
    - typed-process
    - unliftio
    - validity
    - validity-aeson
    - yaml

executables:
  declops:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - declops

tests:
  declops-test:
    main: Spec.hs
    build-tools: sydtest-discover
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - autodocodec
    - autodocodec-yaml
    - declops
    - declops-provider
    - declops-provider-gen
    - genvalidity-aeson
    - genvalidity-path
    - genvalidity-sydtest
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - monad-logger
    - mtl
    - path
    - path-io
    - persistent-sqlite
    - safe-coloured-text
    - sydtest
    - sydtest-persistent-sqlite
    - text
