name: declops
version: 0.0.0.0

data-files:
- nix-bits/**/*.nix

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
    - aeson
    - aeson-pretty
    - autodocodec
    - autodocodec-yaml
    - bytestring
    - containers
    - declops-provider
    - declops-provider-local
    - declops-provider-virtualbox
    - envparse
    - monad-logger
    - mtl
    - optparse-applicative
    - path
    - path-io
    - safe-coloured-text
    - safe-coloured-text-layout
    - safe-coloured-text-terminfo
    - text
    - typed-process
    - unliftio
    - validity
    - yaml

executables:
  declops:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - declops
