- ignore:
    name: "Use newtype instead of data"
- ignore:
    name: "Use &&"
- ignore:
    name: "Use ++"
- ignore:
    name: "Use const"
- ignore:
    name: "Use unless"
- ignore:
    name: "Avoid lambda"
