resolver: lts-18.16
packages:
- declops
- declops-provider
- declops-provider-gen
- declops-provider-local
- declops-provider-test
- declops-provider-virtualbox

- declops-nix-test

extra-deps:
- github: NorfairKing/autodocodec
  commit: 38bd4865ff2dd40d342141b7fde9319f835d98c6
  subdirs:
  - autodocodec
  - autodocodec-schema
  - autodocodec-yaml
- github: NorfairKing/safe-coloured-text
  commit: 71c5940a3b84eeb498304d8e584e7638f875d51b
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-terminfo
- github: NorfairKing/sydtest
  commit: a446095558bc9f67bc3b8ca2e9ce230150c049ff
  subdirs:
  - sydtest
  - sydtest-aeson
  - sydtest-discover
  - sydtest-hspec
  - sydtest-persistent
  - sydtest-persistent-sqlite
  - sydtest-process
  - sydtest-servant
  - sydtest-typed-process
  - sydtest-wai
  - sydtest-yesod
- github: NorfairKing/validity
  commit: 160e846cc5de8e92e6758172da341f5d81fe0374
  subdirs:
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-persistent
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-path
  - genvalidity-persistent
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-sydtest
  - genvalidity-sydtest-aeson
  - genvalidity-sydtest-hashable
  - genvalidity-sydtest-lens
  - genvalidity-sydtest-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector

nix:
  shell-file: shell.nix
  pure: false
