name: declops-provider
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
    - aeson
    - autodocodec
    - monad-logger
    - path
    - persistent-sqlite
    - text
    - validity
    - validity-text
