name: declops-provider-virtualbox
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - autodocodec
    - bytestring
    - declops-provider
    - path
    - path-io
    - text
    - typed-process
    - uuid
    - validity
    - validity-path
    - validity-text
    - validity-uuid
