name: declops-provider-virtualbox-gen
version: 0.0.0.0

extra-source-files:
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
    - declops-provider-virtualbox
    - genvalidity
    - genvalidity-path
    - genvalidity-text
    - genvalidity-uuid

tests:
  declops-provider-virtualbox-test:
    main: Spec.hs
    build-tools: sydtest-discover
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - declops-provider-test
    - declops-provider-virtualbox
    - declops-provider-virtualbox-gen
    - genvalidity-path
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-uuid
    - sydtest
