name: declops-provider-virtualbox-test
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
    - declops-provider-virtualbox
    - declops-provider-virtualbox-gen

tests:
  declops-provider-virtualbox-test:
    main: Spec.hs
    build-tools: sydtest-discover
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - aeson
    - autodocodec
    - bytestring
    - declops-provider-test
    - declops-provider-virtualbox
    - genvalidity-path
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-uuid
    - path
    - path-io
    - sydtest
    - text
    - typed-process
    - uuid
