name: declops-provider-test
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
    - QuickCheck
    - aeson
    - autodocodec
    - autodocodec-yaml
    - declops-provider
    - genvalidity-path
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - sydtest
    - text
