name: declops-provider-test
version: 0.0.0.0

extra-source-files:
- test_resources/**/*


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
    - QuickCheck
    - aeson
    - autodocodec
    - autodocodec-yaml
    - declops
    - genvalidity-path
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - path
    - sydtest
    - text

tests:
  declops-provider-test-test:
    main: Spec.hs
    build-tools: sydtest-discover
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - aeson
    - autodocodec
    - autodocodec-yaml
    - declops
    - declops-provider-test
    - genvalidity-path
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - path
    - sydtest
    - text
